---

- name: Copy interfaces configuration
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    backup: yes

- name: Sleep for server to disconnect
  pause:
    seconds: 5

## - name: Bring up eth1
##  shell: ifdown eth1 && ifup eth1

- name: reboot
  reboot:
    pre_reboot_delay: 60

- name: Flush Handlers, best practice
  meta: flush_handlers
